# Generated by Django 6.0 on 2026-01-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactiontype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='debit_or_credit',
            field=models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], default='DR', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactiontype'),
        ),
    ]
