# Generated by Django 6.0 on 2026-01-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_account_transaction_debit_or_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontype',
            old_name='transaction_type',
            new_name='debit_or_credit',
        ),
    ]
