# Generated by Django 6.0 on 2026-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_transaction_type_transactiontype_debit_or_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
