# Generated by Django 6.0 on 2026-01-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('sales', '0012_remove_invoice_bill_payments_and_more'),
        ('transactions', '0006_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase'),
        ),
    ]
