# Generated by Django 6.0 on 2026-01-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_invoice_transaction_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ref_model',
        ),
    ]
