# Generated by Django 6.0 on 2026-01-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logicconfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logicconfig',
            old_name='value',
            new_name='key',
        ),
    ]
