# Generated by Django 6.0 on 2026-01-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logicconfig', '0002_rename_value_logicconfig_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logicconfig',
            old_name='description',
            new_name='value',
        ),
    ]
