# Generated by Django 6.0 on 2026-01-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logicconfig', '0003_rename_description_logicconfig_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
