# Generated by Django 6.0 on 2026-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_dateendinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateendinventory',
            name='changes_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
