# Generated by Django 6.0 on 2026-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_dateendinventory_changes_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('items', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='dateendinventory',
            name='changes_items',
        ),
    ]
