# Generated by Django 6.0 on 2026-01-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
