# Generated by Django 6.0 on 2026-01-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_delete_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
