# Generated by Django 6.0 on 2026-01-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_items_alter_purchase_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_amount',
        ),
    ]
