# Generated by Django 6.0 on 2026-01-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_delete_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='combo_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_full',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
