# Generated by Django 6.0 on 2026-01-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_combo_info_invoice_items_invoice_items_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surcharge',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='surcharge',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
