# Generated by Django 6.0 on 2026-01-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_name_surcharge_description_surcharge_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='chosen_discount_method',
        ),
    ]
