# Generated by Django 6.0 on 2026-01-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_invoice_chosen_discount_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items_full',
        ),
    ]
