# Generated by Django 6.0 on 2026-01-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_invoice_items_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='combo_info',
        ),
    ]
