# Generated by Django 6.0 on 2026-01-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_invoice_combo_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transport_company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
