# Generated by Django 6.0 on 2026-01-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_invoice_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
