# Generated by Django 6.0 on 2026-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_invoice_amount_paid_by_customer_invoice_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_payments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transport_fee_payments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
