# Generated by Django 6.0 on 2026-01-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_invoice_bill_payments_invoice_transport_fee_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bill_payments',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='transport_fee_payments',
        ),
    ]
