# Generated by Django 6.0 on 2026-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_invoice_bill_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ecom_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ecom_feestructure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
