# Generated by Django 6.0 on 2026-01-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_invoice_ecom_fee_invoice_ecom_feestructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
