# Generated by Django 6.0 on 2026-01-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_invoice_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid_by_customer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid_transport_company',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_method_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ecom_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_surcharge',
            field=models.IntegerField(default=0),
        ),
    ]
