# Generated by Django 6.0 on 2026-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_invoice_amount_paid_by_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='changes_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
