# Generated by Django 6.0 on 2026-01-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_invoice_changes_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='changes_items',
        ),
    ]
