# Generated by Django 6.0 on 2026-01-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='code',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='code',
        ),
    ]
