# Generated by Django 6.0 on 2026-01-09 09:54

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_birthday_customer_email_customer_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default=customers.models.generate_customer_code, max_length=50, unique=True),
        ),
    ]
