# Generated by Django 6.0 on 2026-01-10 08:26

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, default=customers.models.generate_customer_code, max_length=50, null=True, unique=True),
        ),
    ]
